// Code generated by db2go. DO NOT EDIT.
// https://github.com/civet148/sqlca

package loader

const TableNameRunConfig = "run_config" //运行参数表

const (
	RUN_CONFIG_COLUMN_ID           = "id"
	RUN_CONFIG_COLUMN_CONFIG_NAME  = "config_name"
	RUN_CONFIG_COLUMN_CONFIG_KEY   = "config_key"
	RUN_CONFIG_COLUMN_CONFIG_VALUE = "config_value"
	RUN_CONFIG_COLUMN_REMARK       = "remark"
	RUN_CONFIG_COLUMN_DELETED      = "deleted"
	RUN_CONFIG_COLUMN_CREATED_TIME = "created_time"
)

type RunConfigDO struct {
	Id          int32  `json:"id" db:"id" bson:"id"`                                                //自增ID
	ConfigName  string `json:"config_name" db:"config_name" bson:"config_name"`                     //配置名称
	ConfigKey   string `json:"config_key" db:"config_key" bson:"config_key"`                        //配置KEY
	ConfigValue string `json:"config_value" db:"config_value" bson:"config_value"`                  //配置VALUE
	Remark      string `json:"remark" db:"remark" bson:"remark"`                                    //配置备注
	Deleted     bool   `json:"deleted" db:"deleted" bson:"deleted"`                                 //是否已删除(0=否 1=是)
	CreatedTime string `json:"created_time" db:"created_time" sqlca:"readonly" bson:"created_time"` //创建时间
}

func (do *RunConfigDO) GetId() int32            { return do.Id }
func (do *RunConfigDO) SetId(v int32)           { do.Id = v }
func (do *RunConfigDO) GetConfigName() string   { return do.ConfigName }
func (do *RunConfigDO) SetConfigName(v string)  { do.ConfigName = v }
func (do *RunConfigDO) GetConfigKey() string    { return do.ConfigKey }
func (do *RunConfigDO) SetConfigKey(v string)   { do.ConfigKey = v }
func (do *RunConfigDO) GetConfigValue() string  { return do.ConfigValue }
func (do *RunConfigDO) SetConfigValue(v string) { do.ConfigValue = v }
func (do *RunConfigDO) GetRemark() string       { return do.Remark }
func (do *RunConfigDO) SetRemark(v string)      { do.Remark = v }
func (do *RunConfigDO) GetDeleted() bool        { return do.Deleted }
func (do *RunConfigDO) SetDeleted(v bool)       { do.Deleted = v }
func (do *RunConfigDO) GetCreatedTime() string  { return do.CreatedTime }
func (do *RunConfigDO) SetCreatedTime(v string) { do.CreatedTime = v }

/*
CREATE TABLE `run_config` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `config_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '配置名称',
  `config_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '配置KEY',
  `config_value` text COLLATE utf8mb4_unicode_ci COMMENT '配置VALUE',
  `remark` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '配置备注',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除(0=否 1=是)',
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_NAME_KEY` (`config_name`,`config_key`)
) ENGINE=InnoDB AUTO_INCREMENT=131 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运行参数表';
*/
